const puppeteer = require('puppeteer-core');
const URL = 'https://ttungl.github.io/civics-app/';
const out = []; const ok = (n, c, i='') => out.push(`${c ? 'PASS' : 'FAIL'} ${n}${i !== '' ? ' :: ' + i : ''}`);
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const b = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', userDataDir: './live-profile' });
  const p = await b.newPage(); const errs = [];
  p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); }); p.on('pageerror', e => errs.push(e.message));
  await p.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true, deviceScaleFactor: 3 });
  const res = await p.goto(URL, { waitUntil: 'networkidle0' });
  ok('HTTPS 200', res.status() === 200 && p.url().startsWith('https://'), p.url());
  await p.evaluate(() => navigator.serviceWorker.ready); await sleep(1500);
  const sw = await p.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return { active: !!(r && r.active), scope: r && r.scope, caches: await caches.keys(), n: (await (await caches.open((await caches.keys())[0])).keys()).length }; });
  ok('Service worker active, scoped to /civics-app/', sw.active && sw.scope === URL, JSON.stringify(sw));
  const cdp = await p.target().createCDPSession();
  const man = await cdp.send('Page.getAppManifest');
  ok('Manifest parsed without errors', man.url.endsWith('manifest.webmanifest') && man.errors.length === 0, JSON.stringify(man.errors));
  const inst = await cdp.send('Page.getInstallabilityErrors');
  ok('Installable (Chrome installability errors = none)', inst.installabilityErrors.length === 0, JSON.stringify(inst.installabilityErrors));
  const meta = await p.evaluate(() => Object.fromEntries([...document.querySelectorAll('meta[property^="og:"],meta[name^="twitter:"],meta[name=description],meta[name=apple-mobile-web-app-capable],meta[name=apple-mobile-web-app-title]')].map(m => [m.getAttribute('property') || m.name, m.content])));
  ok('OG/Twitter tags present', meta['og:title'] && meta['og:image'] === URL + 'og-image.png' && meta['twitter:card'] === 'summary_large_image', meta['og:title']);
  // Use app online, then go offline
  await p.goto(URL + '#study'); await sleep(500); await p.keyboard.press('ArrowRight'); await sleep(400);
  await p.setOfflineMode(true);
  await p.reload({ waitUntil: 'load' }); await sleep(600);
  const off = await p.evaluate(() => ({ title: document.title, q: document.querySelector('#fc-q').textContent, n: QUESTIONS.length, icon: document.querySelector('.tab svg') !== null }));
  ok('Offline reload works (airplane mode)', off.n === 128 && off.q.length > 10, off.q);
  const p2 = await b.newPage(); await p2.setOfflineMode(true);
  const r2 = await p2.goto(URL + '#review', { waitUntil: 'load' }).catch(e => null); await sleep(500);
  ok('Offline cold open in new tab', r2 && (await p2.evaluate(() => document.querySelectorAll('details.qrow').length)) === 128);
  const img = await p2.evaluate(async () => { const r = await fetch('apple-touch-icon.png'); return r.ok; });
  ok('Offline icons served from cache', img);
  await p2.close(); await p.setOfflineMode(false);
  ok('Progress survived offline reload', await p.evaluate(() => Object.keys(JSON.parse(localStorage.getItem('civics:v1')).p).length) >= 1);
  ok('No console errors on live site', errs.length === 0, errs.join(' | '));
  const og = await p.goto(URL + 'og-image.png'); ok('og-image reachable', og.status() === 200 && og.headers()['content-type'] === 'image/png');
  await b.close();
  console.log(out.join('\n'));
})().catch(e => { console.error(e); process.exit(1); });
